[phases.build]
cmds = [
  "cp package.json.deploy package.json",
  "cp vite.config.deploy.ts vite.config.ts", 
  "npm install",
  "npm run build"
]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"