[variables]
NODE_ENV = "production"
PORT = "8080"

[phases.build]
dependsOn = ["install"]
cmds = [
  "cp package.json.deploy package.json",
  "cp client/index.deploy.html client/index.html",
  "mkdir -p dist",
  "npm run build",
  "ls -la dist/",
  "cat dist/index.js | head -20"
]

[phases.install]
cmds = ["npm ci --include=dev"]

[start]
cmd = "PORT=8080 npm start"